# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_address',
            field=models.CharField(max_length=46),
        ),
    ]
