# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='the book is about', max_length=255),
            preserve_default=False,
        ),
    ]
