# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-20 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='books',
            field=models.ManyToManyField(related_name='publisher', to='example.Book'),
        ),
    ]
