# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-20 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_author_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='notes', max_length=300),
            preserve_default=False,
        ),
    ]
