# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-20 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_author_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='Last', max_length=255),
            preserve_default=False,
        ),
    ]
