# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-22 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='MyUser',
        ),
    ]
